# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when running gradle from the command line,
# check for unexpected changes: run gradle tasks --all to see all available gradle tasks,
# or update the IDEA gradle project settings.
# 1. All your custom properties must come BEFORE the defaults (defaults commented in the file)
# 2. A properties file is typically stored at the root of the project
# See https://gradle.org/releases
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m
org.gradle.parallel=true
org.gradle.daemon=true
kotlin.code.style=official
